2025-08-05 04:38:02,299 INFO    Thread-14 :53592 [wandb_setup.py:_flush():68] Configure stats pid to 53592
2025-08-05 04:38:02,299 INFO    Thread-14 :53592 [wandb_setup.py:_flush():68] Loading settings from /home/mmendieta/.config/wandb/settings
2025-08-05 04:38:02,299 INFO    Thread-14 :53592 [wandb_setup.py:_flush():68] Loading settings from /home/mmendieta/violence_prediction/Scripts/wandb/settings
2025-08-05 04:38:02,300 INFO    Thread-14 :53592 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True', 'project': 'rf_grid_search', 'entity': 'npsdaor', 'root_dir': '/home/mmendieta/violence_prediction/Scripts', 'run_id': 'uas2wb30', 'sweep_param_path': '/home/mmendieta/violence_prediction/Scripts/wandb/sweep-l7kstfg7/config-uas2wb30.yaml', 'sweep_id': 'l7kstfg7'}
2025-08-05 04:38:02,300 INFO    Thread-14 :53592 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2025-08-05 04:38:02,300 INFO    Thread-14 :53592 [wandb_init.py:_log_setup():476] Logging user logs to /home/mmendieta/violence_prediction/Scripts/wandb/run-20250805_043802-uas2wb30/logs/debug.log
2025-08-05 04:38:02,300 INFO    Thread-14 :53592 [wandb_init.py:_log_setup():477] Logging internal logs to /home/mmendieta/violence_prediction/Scripts/wandb/run-20250805_043802-uas2wb30/logs/debug-internal.log
2025-08-05 04:38:02,300 INFO    Thread-14 :53592 [wandb_init.py:_jupyter_setup():426] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f2a86f539d0>
2025-08-05 04:38:02,301 INFO    Thread-14 :53592 [wandb_init.py:init():516] calling init triggers
2025-08-05 04:38:02,301 INFO    Thread-14 :53592 [wandb_init.py:init():519] wandb.init called with sweep_config: {'criterion': 'gini', 'min_samples_leaf': 5, 'min_samples_split': 10, 'n_estimators': 250}
config: {}
2025-08-05 04:38:02,301 INFO    Thread-14 :53592 [wandb_init.py:init():569] starting backend
2025-08-05 04:38:02,301 INFO    Thread-14 :53592 [wandb_init.py:init():573] setting up manager
2025-08-05 04:38:02,307 INFO    Thread-14 :53592 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-08-05 04:38:02,312 INFO    Thread-14 :53592 [wandb_init.py:init():580] backend started and connected
2025-08-05 04:38:02,331 INFO    Thread-14 :53592 [wandb_run.py:_config_callback():1160] config_cb None None {'criterion': 'gini', 'min_samples_leaf': 5, 'min_samples_split': 10, 'n_estimators': 250}
2025-08-05 04:38:02,354 INFO    Thread-14 :53592 [wandb_run.py:_label_probe_notebook():1113] probe notebook
2025-08-05 04:38:02,354 INFO    Thread-14 :53592 [wandb_init.py:init():658] updated telemetry
2025-08-05 04:38:04,048 INFO    Thread-14 :53592 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2025-08-05 04:38:04,284 INFO    Thread-14 :53592 [wandb_run.py:_on_init():2000] communicating current version
2025-08-05 04:38:04,348 INFO    Thread-14 :53592 [wandb_run.py:_on_init():2004] got version response upgrade_message: "wandb version 0.21.0 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2025-08-05 04:38:04,348 INFO    Thread-14 :53592 [wandb_init.py:init():728] starting run threads in backend
2025-08-05 04:38:04,487 INFO    Thread-14 :53592 [wandb_run.py:_console_start():1980] atexit reg
2025-08-05 04:38:04,488 INFO    Thread-14 :53592 [wandb_run.py:_redirect():1838] redirect: SettingsConsole.WRAP_RAW
2025-08-05 04:38:04,488 INFO    Thread-14 :53592 [wandb_run.py:_redirect():1903] Wrapping output streams.
2025-08-05 04:38:04,488 INFO    Thread-14 :53592 [wandb_run.py:_redirect():1925] Redirects installed.
2025-08-05 04:38:04,489 INFO    Thread-14 :53592 [wandb_init.py:init():765] run started, returning control to user process
2025-08-05 12:10:07,961 ERROR   Thread-7  :53592 [internal_api.py:execute():216] 502 response executing GraphQL.
2025-08-05 12:10:07,961 ERROR   Thread-7  :53592 [internal_api.py:execute():217] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2025-08-05 16:12:30,468 ERROR   Thread-7  :53592 [internal_api.py:execute():216] 502 response executing GraphQL.
2025-08-05 16:12:30,469 ERROR   Thread-7  :53592 [internal_api.py:execute():217] 
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

2025-08-05 21:43:27,476 INFO    Thread-14 :53592 [wandb_run.py:_finish():1746] finishing run npsdaor/rf_grid_search/uas2wb30
2025-08-05 21:43:27,477 INFO    Thread-14 :53592 [jupyter.py:save_history():448] not saving jupyter history
2025-08-05 21:43:27,477 INFO    Thread-14 :53592 [jupyter.py:save_ipynb():378] not saving jupyter notebook
2025-08-05 21:43:27,477 INFO    Thread-14 :53592 [wandb_init.py:_jupyter_teardown():408] cleaning up jupyter logic
2025-08-05 21:43:27,477 INFO    Thread-14 :53592 [wandb_run.py:_atexit_cleanup():1949] got exitcode: 0
2025-08-05 21:43:27,478 INFO    Thread-14 :53592 [wandb_run.py:_restore():1932] restore
2025-08-05 21:43:27,478 INFO    Thread-14 :53592 [wandb_run.py:_restore():1938] restore done
2025-08-05 21:43:31,059 INFO    Thread-14 :53592 [wandb_run.py:_footer_history_summary_info():3377] rendering history
2025-08-05 21:43:31,059 INFO    Thread-14 :53592 [wandb_run.py:_footer_history_summary_info():3409] rendering summary
2025-08-05 21:43:31,069 INFO    Thread-14 :53592 [wandb_run.py:_footer_sync_info():3333] logging synced files
