2025-07-23 19:43:33,868 INFO    StreamThr :18318 [internal.py:wandb_internal():88] W&B internal server running at pid: 18318, started at: 2025-07-23 19:43:33.867596
2025-07-23 19:43:33,874 DEBUG   HandlerThread:18318 [handler.py:handle_request():138] handle_request: status
2025-07-23 19:43:34,044 DEBUG   SenderThread:18318 [sender.py:send_request():317] send_request: status
2025-07-23 19:43:34,047 DEBUG   SenderThread:18318 [sender.py:send():303] send: header
2025-07-23 19:43:34,047 INFO    WriterThread:18318 [datastore.py:open_for_write():75] open: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250723_194333-1abxfi47/run-1abxfi47.wandb
2025-07-23 19:43:34,047 DEBUG   SenderThread:18318 [sender.py:send():303] send: run
2025-07-23 19:43:34,460 INFO    SenderThread:18318 [dir_watcher.py:__init__():216] watching files in: /home/mmendieta/violence_prediction/Scripts/wandb/run-20250723_194333-1abxfi47/files
2025-07-23 19:43:34,460 INFO    SenderThread:18318 [sender.py:_start_run_threads():928] run started: 1abxfi47 with start time 1753325013.861439
2025-07-23 19:43:37,046 INFO    MainThread:18318 [internal.py:handle_exit():78] Internal process exited
2025-07-23 19:43:37,047 WARNING MsgRouterThr:18318 [router.py:message_loop():74] EOFError seen in message_loop
